version: '3.8'

services:
  app:
    build: .
    container_name: cristofolini-app
    ports:
      - "80:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=j|jSP!r4B`:0O34+&+/
      - DB_NAME=cristofolini_db
      - JWT_SECRET=cristofolini-secret-key-2026-producao
      - NODE_ENV=production        # era "development"
    restart: unless-stopped        # sobe sozinho se a VM reiniciar
    volumes:
      - uploads_data:/app/public/uploads
      

  db:
    image: mysql:8
    container_name: cristofolini-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=j|jSP!r4B`:0O34+&+/
      - MYSQL_DATABASE=cristofolini_db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  uploads_data: